global:
  licenseplate: c57b11
  environment: dev
  imagestreamtag: develop
  vault_engine: nonprod
  dockerhost: image-registry.openshift-image-registry.svc:5000
  stage: qa
  vault_requests_cpu: 5m   # default: 250m
  vault_requests_mem: 20Mi    # default: 64Mi
  vault_limits_cpu: 10m      # default: 500m
  vault_limits_mem: 64Mi      # default: 128Mi


cmf-apigateway:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-breadcrumb:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-component:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-headerfooter:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-metadata:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-navigation:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-node:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-notification:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-orchestrator:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-pagesummary:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-pagecache:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-search:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-security:
  replicas: "1"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"

cmf-tokengenerator:
  replicas: "0"
  cpu_limit: "300m"
  memory_limit: "750Mi"
  cpu_requests: "150m"
  memory_requests: "575Mi"
