# This secret and corresponding values file that holds "secrets" is for illustration purposes and to provide a complete solution.
# TODO: Update this in the k8s secrets with proper secrets or better yet use vault to store your data. I'll leave this as an exercise for you to implement on your own.
# More details on how to use BCGov't vault can be found here: https://github.com/bashbang/cloudops/tree/main/vault-openshift-bcgov/microservice
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}-creds
  namespace: {{ .Values.license_plate }}-{{ .Values.environment }}
  labels:
    {{- include "chart.common-labels" . }}
stringData:
  replication-username: replication
  replication-password: {{ .Values.replication_password }}
  superuser-username: postgres
  superuser-password: {{ .Values.superuser_password }}
  app-db-name: registry
  app-db-username: myapp
  app-db-password: password
