# Use the official image as a parent image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

RUN apt-get -y update ;\
    apt-get -y upgrade

COPY HelloWorld/HelloWorld.csproj ./
RUN dotnet restore

COPY HelloWorld/ ./

RUN dotnet publish -c Release -o out -r linux-musl-x64 --self-contained false

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "HelloWorld.dll"]
