FROM python:3.12-slim-bullseye
# FROM --platform=linux/amd64 python:3.12-slim-bullseye
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install \
      python3-pip \
      curl \
      vim && \
    rm -rf /var/lib/apt/list/*

COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

SHELL ["/bin/bash", "-c"]

COPY main.py main.py

EXPOSE 5000

ENTRYPOINT ["python", "main.py"]
