FROM image-registry.openshift-image-registry.svc:5000/286498-dev/ubuntu

# RUN apt-get -y update \
#     && apt-get -y upgrade \
#     && apt-get install -y build-essential \
#     && apt-get install -y git