version: "3.7"
services:
  patroni:
      container_name: postgresql
      build:
        context: ./
        dockerfile: Dockerfile
        network: host
      user: postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
      ports:
          - "5432:5432"
      command: ["postgres", "-c", "log_statement=all"]
      networks:
          - backend
      healthcheck:
          test: ["CMD-SHELL", "pg_isready"]
          interval: 10s
          timeout: 5s
          retries: 5

networks:
    backend:
        driver: "bridge"
