apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: p-git-collin-test
spec:
  description: |
    prints the README.md from the selected repo & branch
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: branch-name
      type: string
      description: The git branch to clone.
  workspaces:
    - name: shared-data
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.
    - name: ssh-creds
      description: |
        This workspace will provide ssh credentials to the git-clone task.
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      - name: ssh-directory
        workspace: ssh-creds
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch-name)
#    - name: cat-readme
#      runAfter: ["fetch-repo"] # Wait until the clone is done before reading the readme.
#      workspaces:
#      - name: source
#        workspace: shared-data
#      taskSpec:
#        workspaces:
#        - name: source
#        steps:
#        - image: zshusers/zsh:4.3.15
#          script: |
#            #!/usr/bin/env zsh
#            cat $(workspaces.source.path)/README.md
