kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app: {{ .Values.app_name }}
    cluster-name: {{ .Values.license_plate }}
    app.kubernetes.io/name: patroni
    app.kubernetes.io/component: database
  name: {{ .Values.app_name }}
  namespace: {{ .Values.license_plate }}-dev
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ .Values.app_name }}
    cluster-name: {{ .Values.license_plate }}
    app.kubernetes.io/name: patroni
    app.kubernetes.io/component: database
  name: {{ .Values.app_name }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - patch
      - update
      - create
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ .Values.app_name }}
    cluster-name: {{ .Values.license_plate }}
    app.kubernetes.io/name: patroni
    app.kubernetes.io/component: database
  name: {{ .Values.app_name }}
  namespace: {{ .Values.license_plate }}-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.app_name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.app_name }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ .Values.app_name }}
    cluster-name: {{ .Values.license_plate }}
    app.kubernetes.io/name: patroni
    app.kubernetes.io/component: database
  name: {{ .Values.app_name }}-image-puller
  namespace: {{ .Values.license_plate }}-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
  - kind: ServiceAccount
    name: {{ .Values.app_name }}
    namespace: {{ .Values.license_plate }}-dev
