apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.app_name }}
    cluster-name: {{ .Values.app_name }}
  name: {{ .Values.app_name }}-creds
stringData:
  replication-username: replication
  replication-password: {{ .Values.replication_password }}
  superuser-username: postgres
  superuser-password: {{ .Values.superuser_password }}
  app-db-name: registry
  app-db-username: myapp
  app-db-password: password
