kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{ .Values.app_name }}
    name: {{ .Values.app_name }}
    cluster-name: {{ .Values.license_plate }}
  name: {{ .Values.app_name }}-master
spec:
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cluster-name: {{ .Values.app_name }}
    role: master
    app.kubernetes.io/name: patroni
  sessionAffinity: None
  type: ClusterIP
