kind: TransportServerClaim
apiVersion: porter.devops.gov.bc.ca/v1alpha1
metadata:
  name: {{ .Values.app_name }}-postgres-tsc
  namespace: {{ .Values.license_plate }}-dev
spec:
  monitor:
    interval: 10
    timeout: 10
    type: tcp
  service: {{ .Values.app_name }}
  servicePort: 5432