version: "3.8"
services:
  pytorch:
    container_name: pytorch
    image: pytorch:latest
    build:
      context: .
      dockerfile: Dockerfile.yaml
    ports:
      - 8080:8080
    networks:
      - pytorch
networks:
    pytorch:
      driver: bridge