# Log into openshift and select the correct namespace
# cmd: oc apply -f ./deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: util
  labels:
    app: util
spec:
  replicas: 1
  selector:
    matchLabels:
      app: util
  template:
    metadata:
      labels:
        app: util
    spec:
      containers:
      - name: util
        image: ghcr.io/bashbang/util:release
        volumeMounts:
          - name: kube
            mountPath: /.kube
          - name: test3
            mountPath: /test3
          - name: test4
            mountPath: /test4
        command: ["tail", "-f", "/dev/null"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
          requests:
            cpu: "50m"
            memory: "100Mi"
      volumes:
      - name: kube
        emptyDir: {}
      - name: test3
        emptyDir: {}
      - name: test4
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
