# This action produces a docker artifact of my utility pod used in k8s.
name: Build Util Container

on:
  push:
    branches: ['release']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:

      # - name: Checkout code
      #   uses: actions/checkout@v3
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: ./docker/util/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ github.actor }}/util:latest
