name: Build Midas Probe

on:
  push:
    branches: [pickabranch]
    paths-ignore: [midas-probe/openshift]
  workflow_dispatch:

jobs:
  build:
    name: Build Midas Probe
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image with docker-compose
        working-directory: midas-probe
        run: |
          docker-compose build midas-probe

      - name: Login to OC4 Gold Docker
        uses: docker/login-action@v1
        with:
          registry: image-registry.apps.gold.devops.gov.bc.ca
          username: serviceaccount
          password: ${{ secrets.GOLD_TOOLS_SA_GHA_TOKEN }}

      - name: Tag and Push Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker tag midas-probe image-registry.apps.gold.devops.gov.bc.ca/${{ secrets.LICENSEPLATE }}-tools/midas-probe:dev
          docker push image-registry.apps.gold.devops.gov.bc.ca/${{ secrets.LICENSEPLATE }}-tools/midas-probe --all-tags
