name: GHA Runner Test

on:
  workflow_dispatch

jobs:
  RunBuild:
    runs-on: ububtu-latest
    name: GHA Runner
    steps:
      - name: Obtain code from git
        uses: actions/checkout@v2
      