name: Patroni Build
# This workflow runs if helm changes were made to either a values file or a chart template change.
on:
  workflow_dispatch:

jobs:
  RunBuild:
    runs-on: ubuntu-latest
    name: Run Patroni Build
    steps:
      - name: Obtain code from git
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build image with docker-compose
        working-directory: ./patroni/docker
        run: |
          docker-compose build patroni

      # - name: Login to OC4 Silver
      #   uses: docker/login-action@v2
      #   with:
      #     registry: image-registry.apps.silver.devops.gov.bc.ca
      #     username: serviceaccount
      #     password: ${{ secrets.48aa05-dev_silver-token }}

      # - name: Tag and Push "Develop-Silver" Docker image
      #   run: |
      #     docker tag cmf-microservices_patroni image-registry.apps.silver.devops.gov.bc.ca/48aa05-dev/patroni:latest
      #     docker push image-registry.apps.silver.devops.gov.bc.ca/48aa05-dev-tools/patroni:latest
