name: testing

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

  strategy:
    matrix:
      stage: [rt, qa]
      environ: ["TESTING","PRODUCTION"]

  steps:
    - name: Test Run
      run: |
        echo STAGE=${{ matrix.stage }}
        echo ENVIRO=${{ matrix.enviro }}
        echo secret=${{ env[format('secrets.MY_{0}_SECRET', matrix.enviro)] }}
