name: testing

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - name: TestRun
        run: |
          echo STAGE=${{ secrets.stage }}
          echo ENVIRO=${{ secrets.enviro }}
