name: testing

on:
  workflow_dispatch:

jobs:
  gold:
    runs-on: ubuntu-latest
    environment: gold

    steps:
      - name: TestRun
        run: |
          echo STAGE=${{ secrets.stage }}
          echo ENVIRO=${{ secrets.enviro }}

  golddr:
    runs-on: ubuntu-latest
    environment: golddr

    steps:
      - name: TestRun
        run: |
          echo STAGE=${{ secrets.stage }}
          echo ENVIRO=${{ secrets.enviro }}
