name: testing

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stage: [rt, qa]
        enviro: ["TESTING","PRODUCTION"]

    steps:
      - name: TestRun
        run: |
          echo STAGE=${{ matrix.stage }}
          echo ENVIRO=${{ matrix.enviro }}
          echo secret= '${{ format('secrets.MY_{0}_SECRET', matrix.enviro) }}'
